#!/bin/bash
MODEL=$1
RUNDATE=$2
CACHEDIR=$3

declare -x RUNDATEDIR=${RUNDATE:0:4}/${RUNDATE:4:2}/${RUNDATE:6:2}/${RUNDATE:8:4}
declare -x NCDFCACHEPATH=$DDS_OUTPUT_PATH/$MODEL/netcdf/$RUNDATEDIR/CACHE/

mkdir -p $NCDFCACHEPATH
rsync -av -T /run/user/1001/ $CACHEDIR $NCDFCACHEPATH
